// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjabmVXio6B7jUqpUM4dpcW49Xg2razLg',
    appId: '1:744803540226:web:d9a459ffc31c22db0ab61b',
    messagingSenderId: '744803540226',
    projectId: 'chat-app-44e88',
    authDomain: 'chat-app-44e88.firebaseapp.com',
    storageBucket: 'chat-app-44e88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fNmCJIy88HYEzZCDmNhA0Rljbsp1N5g',
    appId: '1:744803540226:android:374ac045bc12372d0ab61b',
    messagingSenderId: '744803540226',
    projectId: 'chat-app-44e88',
    storageBucket: 'chat-app-44e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FME1abFm-SigPxts4AcgM-0FqssoZQk',
    appId: '1:744803540226:ios:f34a1268913a8fac0ab61b',
    messagingSenderId: '744803540226',
    projectId: 'chat-app-44e88',
    storageBucket: 'chat-app-44e88.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_FME1abFm-SigPxts4AcgM-0FqssoZQk',
    appId: '1:744803540226:ios:f34a1268913a8fac0ab61b',
    messagingSenderId: '744803540226',
    projectId: 'chat-app-44e88',
    storageBucket: 'chat-app-44e88.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
